services:
  stringwave:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: stringwave:latest
    container_name: stringwave
    pull_policy: never
    restart: unless-stopped
    user: stringwave
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - stringwave
    volumes:
      #- ./app.py:/stringwave/app.py
      - ./radio:/stringwave/radio
      # - ./scripts:/stringwave/scripts
      - ./logs:/stringwave/logs
      # - ./dl_data:/stringwave/dl_data/
      # - ./webapp/templates/:/stringwave/webapp/templates/
      # - ./webapp/static/:/stringwave/webapp/static/
      - upload_dir:/stringwave/webapp/static/uploads/
      - ./webapp/static/images/channel_icons:/stringwave/webapp/static/images/channel_icons
      - download_data:/stringwave/dl_data/
      #- ./tests:/stringwave/tests
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - NUM_DAILY_DOWNLOADS=${NUM_DAILY_DOWNLOADS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - DISCOGS_PERSONAL_ACCESS_TOKEN=${DISCOGS_PERSONAL_ACCESS_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - wud.watch=false

  gateway:
    image: nginxinc/nginx-unprivileged:latest
    container_name: stringwave-nginx
    depends_on:
      - stringwave
    networks:
      - stringwave
    restart: unless-stopped
    ports:
      - 10004:8080
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro

  celery:
    build:
      context: .
      dockerfile: build/Dockerfile-celery
    image: stringwave-celery:latest
    container_name: stringwave-celery
    pull_policy: never
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - stringwave
    restart: unless-stopped
    volumes:
      - ./radio:/stringwave/radio
      - ./logs:/stringwave/logs
      # - ./dl_data:/stringwave/dl_data/
      # - ./tasks.py:/stringwave/tasks.py
      - upload_dir:/stringwave/webapp/static/uploads/
      - ./webapp/static/images/channel_icons:/stringwave/webapp/static/images/channel_icons
      - download_data:/stringwave/dl_data/
    environment:
      - NUM_DAILY_DOWNLOADS=${NUM_DAILY_DOWNLOADS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - wud.watch=false

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: stringwave-rabbitmq
    hostname: rabbitmq
    healthcheck:
      #test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_virtual_hosts"]
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      stringwave:
    restart: unless-stopped

  icecast:
    build:
      context: .
      dockerfile: build/Dockerfile-icecast
    image: stringwave-icecast:latest
    container_name: stringwave-icecast
    pull_policy: never
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      stringwave:
    restart: unless-stopped
    labels:
      - wud.watch=false

  postgres:
    image: postgres:17.10
    container_name: stringwave-postgres
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      # - ./postgres_init:/docker-entrypoint-initdb.d
      - ./scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - 5432:5432
    networks:
      - stringwave
    labels:
      - wud.watch=false

  pgloader:
    image: dimitri/pgloader:latest
    networks:
      - stringwave
    profiles:
      - migration
    volumes:
      - ./webapp/instance:/sqlite
    command:
      - pgloader
      - sqlite:///sqlite/stringwave.db
      - postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/stringwave

networks:
  stringwave:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.10.0/24

volumes:
  upload_dir:
  download_data:
