FROM python:3.11.3-slim-bullseye

WORKDIR /stringwave

RUN apt-get update && apt-get upgrade -y
RUN apt-get install ffmpeg -y

COPY requirements-celery.txt ./requirements.txt
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt

RUN groupadd -r --gid 1000 stringwave && useradd -r --uid 1000 -g stringwave stringwave
RUN chsh --shell /usr/sbin/nologin root

COPY radio/ ./radio/
COPY scripts/ ./scripts/
COPY webapp/ ./webapp/
COPY cogmera.py .
COPY pipefeeder.py .
COPY bad_words.py .
COPY tasks.py .
COPY start-celery.sh ./start.sh

RUN export NUM_DAILY_DOWNLOADS=$NUM_DAILY_DOWNLOADS
RUN mkdir dl_data logs /home/stringwave
RUN touch webapp/static/subs.txt \
    webapp/static/move_status \
    dl_data/urls \
    dl_data/search_queries \
    webapp/static/upload_status
RUN chown -R stringwave:stringwave \
	/home/stringwave \
	/stringwave

USER stringwave
ENTRYPOINT [ "bash", "./start.sh" ]
